package com.openclassrooms.paymybuddy.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity representing an account in the system.
 * Contains information about the account's ID and balance.
 */
@Data
@Entity
public class Account {

    /**
     * The unique identifier of the account.
     * Automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The balance of the account.
     * Cannot be null.
     */
    @Column(nullable = false)
    private int balance;
}
