package com.openclassrooms.paymybuddy.model;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing a transaction in the system.
 * Contains details about the transaction such as description, amount, sender, and receiver.
 */
@Data
@Entity
@Table(name = "transactions")
public class Transaction {

    /**
     * The unique identifier of the transaction.
     * Automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The description of the transaction.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String description;

    /**
     * The amount involved in the transaction.
     * Cannot be null.
     */
    @Column(nullable = false)
    private int amount;

    /**
     * The user who initiated the transaction.
     * Represents the sender of the transaction.
     */
    @ManyToOne
    @JoinColumn(name = "senderId")
    private User sender;

    /**
     * The user who receives the transaction.
     * Represents the receiver of the transaction.
     */
    @ManyToOne
    @JoinColumn(name = "receiverId")
    private User receiver;

    /**
     * The timestamp when the transaction was created.
     * Automatically set to the current date and time when the transaction is created.
     */
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime timestamp;
}
